#!/usr/bin/env python3
import sys
import json
from bom import *

"""This method will read the stdin stream. 

Parse will take the first line of the stdin stream and set it to a variable
which will determine the output at the end of the method.

Subsequent lines will be parsed by the BOM class on instantiation. This will
create the neccisary attribues for merge, sort, count functionality. 

Finally a collection of merged and sorted 
"""
def parse():
    lineNum = 0
    output = 0
    bomCollection = []
    invalidInputs = [] # Can be used for future troubleshooting of input stream

    for line in sys.stdin:
        foundDupe = False # For identifying BOMS with dupe MPN and Manufacturer

        if lineNum > 0:
            bom = BOM(line.rstrip())
            if hasattr(bom, 'invalidInputFormat'):
                invalidInputs.append(line.rstrip())
                continue

            # No need to check for duplicates on first BOM.
            if lineNum == 1:
                bomCollection.append(bom)

                # Merge and count BOMS with the same MPN and Manufacturer. 
            else:
                for b in bomCollection:
                    if b.MPN == bom.MPN and b.Manufacturer == bom.Manufacturer:
                        b.ReferenceDesignators.extend(
                                rd for rd in bom.ReferenceDesignators 
                                if rd not in b.ReferenceDesignators)
                        b.NumOccurrences += 1
                        foundDupe = True
                        break
                    
            if not foundDupe:
                bomCollection.append(bom)
            lineNum += 1

        # Set the first line in stream as output variable.
        else:
            output = int(line.rstrip())
            lineNum += 1
    
    idx = 0
    outputList = []
    sortedCollection = sorted(bomCollection, key=lambda b: b.NumOccurrences, reverse=True)

    # Add number of records to outputList equal to 
    # output defined on first line of stream
    while idx < output:
        outputList.append(sortedCollection[idx].__dict__)
        idx += 1
    
    # Print!
    print(json.dumps(outputList, sort_keys=True, indent=4))

parse()